#!/bin/sh

while true; do
    batt=$(acpi --battery | cut -d, -f2 | sed 's/[ % ]//g')
    if [ "$batt" -lt "15" ] && [ -n "$(acpi -a | grep 'off-line')" ]; then
        echo "Warning! Battery: $batt%" > $NOTIFYD_FIFO_PATH
        bspc config focused_border_color `xrq color1`
        sleep 300
    else
        bspc config focused_border_color `xrq color4`
        sleep 900
    fi
done
