#!/bin/sh

. /home/jvillanueva/.zshenv
M=$(bspc query -M | wc -l)
if [[ "$M" == 1 ]]; then
    bspc monitor -d I II III IV V
elif [[ "$M" == 2 ]]; then
    bspc monitor $(bspc query -M | awk NR==1) -d I II III IV V
    bspc monitor $(bspc query -M | awk NR==2) -d VI VII VIII IX
fi

