#!/bin/sh

op=$1
n=${2:-10}

case $op in
    +)
        xbacklight -inc $n
        ;;
    -)
        xbacklight -dec $n
        ;;
    s)
        xbacklight -set $n
        ;;
esac

printf "Brightness: %.0f\n" `xbacklight` >> $NOTIFYD_FIFO_PATH
